// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAucvuuxGXDQ1Xo-ywJ5tsJBWYjictv-GE',
    appId: '1:604803627661:web:fe648b00b43687b699c0c4',
    messagingSenderId: '604803627661',
    projectId: 'vehical-breakdown-app',
    authDomain: 'vehical-breakdown-app.firebaseapp.com',
    storageBucket: 'vehical-breakdown-app.appspot.com',
    measurementId: 'G-EYS4KMV6FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpHJ0YRRjKTHeadYyEWCyZlU3OmBRzixI',
    appId: '1:604803627661:android:2636f6d87290883999c0c4',
    messagingSenderId: '604803627661',
    projectId: 'vehical-breakdown-app',
    storageBucket: 'vehical-breakdown-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUtdyt9RaDaStgCN-2joOvcrevu4l5rS0',
    appId: '1:604803627661:ios:d9e79f528c77cde099c0c4',
    messagingSenderId: '604803627661',
    projectId: 'vehical-breakdown-app',
    storageBucket: 'vehical-breakdown-app.appspot.com',
    iosBundleId: 'com.example.vehicalBreakdownApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUtdyt9RaDaStgCN-2joOvcrevu4l5rS0',
    appId: '1:604803627661:ios:01ec612bd4a425c699c0c4',
    messagingSenderId: '604803627661',
    projectId: 'vehical-breakdown-app',
    storageBucket: 'vehical-breakdown-app.appspot.com',
    iosBundleId: 'com.example.vehicalBreakdownApp.RunnerTests',
  );
}
